
(ql:quickload "lispbuilder-sdl")
(ql:quickload "cl-cairo2")

(load (compile-file "sdl-patch.lisp"))
(load (compile-file "packages.lisp"))
(load (compile-file "scenic-utils.lisp"))
(load (compile-file "scenic-images.lisp"))
(load (compile-file "scenic-events.lisp"))
(load (compile-file "scenic-classes.lisp"))
(load (compile-file "scenic-containers.lisp"))
(load (compile-file "scenic-grid.lisp"))
(load (compile-file "scenic-scene.lisp"))
(load (compile-file "scenic-decorators.lisp"))
(load (compile-file "scenic-buttons.lisp"))
(load (compile-file "scenic-scroll.lisp"))
(load (compile-file "scenic-helpers.lisp"))
(load (compile-file "scenic.lisp"))
(load (compile-file "scenic-test.lisp"))

;; to test (after loading this file)
;; (in-package :scenic-test)
;; (run-all-tests)